### PR TITLE
Support closures as values for `::set()`

### PR DESCRIPTION
**Pull request by borkweb**
This allows us to `Memoize::set()` with a `Closure` as a value, resolving it before setting in the cache. 

### Documentation Updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R7-R20): Updated to include a table of contents and examples using the new `Memoizer` class instead of the deprecated `Memoize` class. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R7-R20) [[2]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L32-R69) [[3]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L63-R103) [[4]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L92-R248)

### Codebase Simplification:
* [`src/Memoize/Config.php`](diffhunk://#diff-d74a854de1146e0d6a492544586d7481f3a36032209c9bd4c7b6224843dcd161L1-L61): Removed the `Config` class in favor of dependency injection for setting drivers and namespaces.
* [`src/Memoize/Contracts/DriverInterface.php`](diffhunk://#diff-fafb983e4ad432744020d6ed11c7e9b00a9fa8804c47876bf3dd27892f0836edL5-R5): Renamed and updated the namespace for consistency.
* [`src/Memoize/Contracts/MemoizerInterface.php`](diffhunk://#diff-66fbb2dce49730c021c72d1c6404aefdf22a7d9b975f4e14699177ab096802bdL5-R15): Renamed and updated the namespace for consistency. [[1]](diffhunk://#diff-66fbb2dce49730c021c72d1c6404aefdf22a7d9b975f4e14699177ab096802bdL5-R15) [[2]](diffhunk://#diff-66fbb2dce49730c021c72d1c6404aefdf22a7d9b975f4e14699177ab096802bdL27-R40)

### New Features:
* [`src/Memoize/Drivers/MemoryDriver.php`](diffhunk://#diff-63a0e4513538fafeb47965814cc2240ca8c69b26ef36ab7bea9aeb59173e6308R7-R47): Modified to support closures as cache values, resolving them before storing. [[1]](diffhunk://#diff-63a0e4513538fafeb47965814cc2240ca8c69b26ef36ab7bea9aeb59173e6308R7-R47) [[2]](diffhunk://#diff-63a0e4513538fafeb47965814cc2240ca8c69b26ef36ab7bea9aeb59173e6308L50-R58)
* [`src/Memoize/Memoizer.php`](diffhunk://#diff-c4e6075c1ba09675160618994321e74cf2b89abcc9a7816a97535311bcfdb88aR1-R80): Introduced a new `Memoizer` class implementing `MemoizerInterface`, replacing the static `Memoize` class.

### Testing Enhancements:
* [`tests/unit/ClosureTest.php`](diffhunk://#diff-fb1332bd1559c020dbded75113082edc59990d6fb7d57918370da63904fa1dfcR1-R66): Added new tests to ensure that closures are correctly resolved and stored in the cache.

### CODE REVIEW

**Review by JasonTheAdams — COMMENTED** [review]
Oh interesting! You took it a slightly different way than I'd meant, which is fine! I originally meant that the function was called _upon setting_, so the driver doesn't matter. What you've done here is even more clever and it effectively makes a dynamic cached value, as the closure is called upon retrieval.

Honestly, I'm trying to decide if this is extremely clever or a caching anti-pattern. 🤔

**Comment by borkweb** [comment]
@JasonTheAdams - tbh, resolving on set would be waaaay simpler and I think I see where you are going with it being a potential anti-pattern. I could see how a result could become unpredictable later based on the moment of resolution.

**Comment by borkweb** [comment]
I went ahead and went the resolve-on-set route for simplification's sake.

**Review by JasonTheAdams — APPROVED** [review]
Looks good! 💪

**Pull request merged**
